### ISSUE TITLE
Roadmap: remains to be implemented for specialization constants

### ISSUE THREAD

**Issue by tomaka** [vulkano-rs/vulkano#262]
- [ ] Add members to `GraphicsPipelineParams`: `vertex_shader_consts`, `fragment_shader_consts`, `geometry_shader_consts` whose types are the template parameters `Vsp`, `Fs` and `Gs`. Note that later we may want to instead use different types that implement `Into<Vsp>`, `Into<Fs>`, `Into<Gs>`, but that's a debatable thing to do so I'll leave it be.
- [ ] Same for `GraphicsPipelineParamsTess` with `Tcs` and `Tes`.
- [ ] Implement loading the specialization constants for the graphics stuff. Just take [this code](https://github.com/tomaka/vulkano/blob/27d23725aefcd3a60f4f1c34455443a5182f587d/vulkano/src/pipeline/compute_pipeline.rs#L56-L62) and [this code](https://github.com/tomaka/vulkano/blob/27d23725aefcd3a60f4f1c34455443a5182f587d/vulkano/src/pipeline/compute_pipeline.rs#L71-L75), and adjust them here: [1](https://github.com/tomaka/vulkano/blob/27d23725aefcd3a60f4f1c34455443a5182f587d/vulkano/src/pipeline/graphics_pipeline/mod.rs#L356) [2](https://github.com/tomaka/vulkano/blob/27d23725aefcd3a60f4f1c34455443a5182f587d/vulkano/src/pipeline/graphics_pipeline/mod.rs#L366) [3](https://github.com/tomaka/vulkano/blob/27d23725aefcd3a60f4f1c34455443a5182f587d/vulkano/src/pipeline/graphics_pipeline/mod.rs#L381) [4](https://github.com/tomaka/vulkano/blob/27d23725aefcd3a60f4f1c34455443a5182f587d/vulkano/src/pipeline/graphics_pipeline/mod.rs#L399) [5](https://github.com/tomaka/vulkano/blob/27d23725aefcd3a60f4f1c34455443a5182f587d/vulkano/src/pipeline/graphics_pipeline/mod.rs#L409). Beware that you must store the `specialization` and `spec_descriptors` objects at the root of the function scope, otherwise they will get destroyed and the pointers to them will become invalid.
- [ ] In `vulkano-shaders/src/entry_point.rs`, add a function that parses the SPIR-V code and generates a struct named `SpecializationConstants` which contains the specialization constants (just a regular struct with public members corresponding to the constants). Make it implement [the `SpecializationConstants` trait](https://github.com/tomaka/vulkano/blob/27d23725aefcd3a60f4f1c34455443a5182f587d/vulkano/src/pipeline/shader.rs#L694-L724). That's obviously the hardest part.
- [ ] Call that function [here](https://github.com/tomaka/vulkano/blob/27d23725aefcd3a60f4f1c34455443a5182f587d/vulkano-shaders/src/entry_point.rs#L40).
- [ ] Replace the first template parameter [here](https://github.com/tomaka/vulkano/blob/27d23725aefcd3a60f4f1c34455443a5182f587d/vulkano-shaders/src/entry_point.rs#L43) (that is `()` for the moment) with `SpecializationConstants`. Same for the 5 other shader types.

The first three and the last three points can be worked upon separately.

**Comment by tomaka** [comment]
This has been implemented in 0.6.1
